:: Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
:: SPDX-License-Identifier: BSD-3-Clause

@echo off
setlocal enabledelayedexpansion

:: Script for signing Windows driver catalog (.cat) files.
::
:: Prerequisites:
::   - Windows SDK (provides signtool.exe)
::   - A valid code signing certificate installed in the certificate store
::   - .cat files generated by build.bat
::
:: Usage:
::   sign.bat <certname>    - Sign all .cat files with the specified certificate

set "SCRIPT_DIR=%~dp0"

if "%~1"=="" (
    echo Error: Certificate subject name is required.
    echo Usage: sign.bat "Certificate Subject Name"
    exit /b 1
)
set "CERT_NAME=%~1"

:: Verify .cat files exist
set "CAT_COUNT=0"
for %%f in ("%SCRIPT_DIR%*.cat") do set /a CAT_COUNT+=1
if %CAT_COUNT% EQU 0 (
    echo Error: No .cat files found. Run build.bat first to generate catalog files.
    exit /b 1
)

:: Locate signtool.exe - check PATH first, then search SDK installation (prefer x64, then x86)
set "SIGNTOOL=signtool"
where signtool >nul 2>&1
if %errorlevel% neq 0 (
    set "SIGNTOOL="
    for /f "delims=" %%i in ('dir /s /b "C:\Program Files (x86)\Windows Kits\10\bin\signtool.exe" 2^>nul ^| findstr /i "\\x64\\"') do (
        if not defined SIGNTOOL set "SIGNTOOL=%%i"
    )
    if not defined SIGNTOOL (
        for /f "delims=" %%i in ('dir /s /b "C:\Program Files (x86)\Windows Kits\10\bin\signtool.exe" 2^>nul ^| findstr /i "\\x86\\"') do (
            if not defined SIGNTOOL set "SIGNTOOL=%%i"
        )
    )
    if not defined SIGNTOOL (
        echo Error: signtool.exe not found. Please install the Windows SDK
        echo and ensure it is in your PATH, or install it to the default location.
        exit /b 1
    )
    echo Found signtool at: !SIGNTOOL!
)

echo ==========================================
echo  Qualcomm USB Driver Catalog Sign Script
echo ==========================================
echo.
echo Certificate: %CERT_NAME%
echo.

set "SIGN_ERRORS=0"
for %%f in ("%SCRIPT_DIR%*.cat") do (
    echo Signing: %%~nxf
    "!SIGNTOOL!" sign /n "%CERT_NAME%" /t http://timestamp.digicert.com /fd SHA256 "%%f"

    if !ERRORLEVEL! EQU 0 (
        echo Successfully signed: %%~nxf
    ) else (
        echo Failed to sign: %%~nxf ^(Error code !ERRORLEVEL!^)
        set /a SIGN_ERRORS+=1
    )
    echo.
)

if !SIGN_ERRORS! GTR 0 (
    echo Signing completed with !SIGN_ERRORS! error^(s^).
    exit /b 1
)

echo Signing completed successfully.
endlocal